# Generated by Django 5.2.8 on 2025-11-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_destinationregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Your Tour Guide', max_length=200)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('site_email', models.EmailField(blank=True, max_length=254)),
                ('site_address', models.TextField(blank=True)),
                ('site_description', models.TextField(blank=True)),
                ('site_metakey', models.TextField(blank=True, help_text='Comma-separated keywords')),
                ('site_metadescription', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
