# Generated by Django 5.2.8 on 2025-11-24 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_country_destinationregion_new_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationregion',
            name='country',
        ),
        migrations.RenameField(
            model_name='destinationregion',
            old_name='new_country',
            new_name='country',
        ),
    ]
