# Generated by Django 5.2.8 on 2025-12-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='display_section',
            field=models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('default', 'Default')], default='default', max_length=20),
        ),
    ]
