# Generated by Django 5.2.8 on 2025-12-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_page_display_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_dk', models.CharField(blank=True, max_length=200)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='feature_sections/')),
                ('is_banner_showing', models.BooleanField(default=True)),
                ('short_description', models.TextField(blank=True)),
                ('short_description_dk', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('description_dk', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('rank', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Section',
                'verbose_name_plural': 'Feature Sections',
                'ordering': ['rank', '-created_at'],
            },
        ),
    ]
