# Generated by Django 5.2.8 on 2025-12-06 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_featuresection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSectionTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_tours', to='accounts.featuresection')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tour')),
            ],
            options={
                'verbose_name': 'Feature Section Tour',
                'verbose_name_plural': 'Feature Section Tours',
                'ordering': ['-created_at'],
                'unique_together': {('feature_section', 'tour')},
            },
        ),
    ]
