# Generated by Django 5.2.8 on 2025-12-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_featuresectiontour'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_dk', models.CharField(blank=True, max_length=200)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='website_menus/')),
                ('is_banner_showing', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('rank', models.IntegerField(default=0)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_open_new_tab', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Website Menu',
                'verbose_name_plural': 'Website Menus',
                'ordering': ['rank', '-created_at'],
            },
        ),
    ]
