# Generated by Django 5.2.8 on 2025-12-06 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_websitemenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_dk', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('rank', models.IntegerField(default=0)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_open_new_tab', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='accounts.websitemenu')),
            ],
            options={
                'verbose_name': 'Website SubMenu',
                'verbose_name_plural': 'Website SubMenus',
                'ordering': ['rank', '-created_at'],
            },
        ),
    ]
