# Generated by Django 5.2.8 on 2025-12-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_websitesubmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemenu',
            name='has_submenu',
            field=models.BooleanField(default=False),
        ),
    ]
