# Generated by Django 5.2.8 on 2025-12-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_websitemenu_has_submenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qus_en', models.TextField(verbose_name='Question (English)')),
                ('qus_dk', models.TextField(blank=True, verbose_name='Question (Danish)')),
                ('ans_en', models.TextField(verbose_name='Answer (English)')),
                ('ans_dk', models.TextField(blank=True, verbose_name='Answer (Danish)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_phone',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
