# Generated by Django 5.2.8 on 2025-12-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_faq_sitesetting_site_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(blank=True, help_text='Main destination image for the country', null=True, upload_to='countries/destinations/'),
        ),
    ]
