# Generated by Django 5.2.8 on 2025-12-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_country_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='app_google',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='fb_link',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='insta_link',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ios_app',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='linkdin_link',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='pintrest_link',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_map',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='x_link',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='websitemenu',
            name='section_type',
            field=models.CharField(choices=[('header', 'Header'), ('footer', 'Footer')], default='header', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_phone',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='toursupplier',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Commission percentage', max_digits=5),
        ),
    ]
