# Generated by Django 5.2.8 on 2025-12-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_sitesetting_app_google_sitesetting_fb_link_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='tour',
            name='map_location',
            field=models.TextField(blank=True, help_text='Enter the Google Maps Embed URL'),
        ),
    ]
