# Generated by Django 5.2.8 on 2026-01-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_sitesetting_site_logo_dark_tour_map_location'),
    ]

    operations = [

        migrations.AddField(
            model_name='toursupplier',
            name='password',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
