# Generated by Django 5.2.8 on 2026-01-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_teammember_sitesetting_site_logo_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='before_discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='before_discount_price_statue',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20),
        ),
        migrations.AddField(
            model_name='tour',
            name='before_discount_price_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
