# Generated by Django 5.2.8 on 2026-01-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_souvenir_sitesetting_site_logo_dark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='souvenir',
            old_name='before_discount_price_status',
            new_name='before_discount_price_statue',
        ),
    ]
