# Generated by Django 5.2.8 on 2026-02-22 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_sitesetting_site_logo_dark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessage',
            name='unique_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customermessage',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.customer'),
        ),
    ]
