# Generated by Django 5.2.8 on 2026-02-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_customermessage_unique_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bike_addons/')),
                ('title', models.CharField(max_length=200)),
                ('title_dk', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('description_dk', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bike Addon',
                'verbose_name_plural': 'Bike Addons',
                'ordering': ['-created_at'],
            },
        ),
    ]


