# Generated by Django 5.2.8 on 2026-02-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_bikeaddon_sitesetting_site_logo_dark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bikes/')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('title_dk', models.CharField(blank=True, max_length=255)),
                ('shortdescription', models.TextField(blank=True)),
                ('shortdescription_dk', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('description_dk', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('show_discount', models.BooleanField(default=False)),
                ('price_before_disount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height_info', models.CharField(blank=True, max_length=100)),
                ('width_info', models.CharField(blank=True, max_length=100)),
                ('gear_info', models.CharField(blank=True, max_length=100)),
                ('is_unisex', models.BooleanField(default=True)),
                ('is_helmet_recommended', models.BooleanField(default=True)),
                ('is_electric', models.BooleanField(default=False)),
                ('top_speed_info', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bike',
                'verbose_name_plural': 'Bikes',
                'ordering': ['-created_at'],
            },
        ),
    ]


