# Generated by Django 5.2.8 on 2026-03-04 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_bike_sitesetting_site_logo_dark'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeAddonPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bikeaddon')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_addons', to='accounts.bike')),
            ],
            options={
                'verbose_name': 'Bike Addon Price',
                'verbose_name_plural': 'Bike Addon Prices',
            },
        ),
    ]
