# Generated by Django 5.2.8 on 2026-03-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_sitesetting_site_logo_dark_bikebooking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='meetoursuides_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_logo_dark',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
