# Generated by Django 5.2.8 on 2026-03-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_sitesetting_meetoursuides_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikebookingaddon',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
