# Generated by Django 5.2.8 on 2026-03-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_bikebookingaddon_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikebooking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bikebooking',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
