# Generated by Django 5.2.8 on 2026-03-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_bikebooking_end_date_bikebooking_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikebooking',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bikebooking',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
