# Generated by Django 5.2.8 on 2026-03-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_bikebooking_end_time_bikebooking_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikebooking',
            name='bike_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
