# Generated by Django 5.2.8 on 2026-03-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_bikebooking_bike_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tour_time_slot',
            field=models.CharField(blank=True, choices=[('9.30-12.00', '9.30-12.00'), ('13.00-15.30', '13.00-15.30'), ('19.30-22.00', '19.30-22.00')], max_length=50, null=True),
        ),
    ]
