# Generated by Django 5.2.8 on 2026-03-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_booking_tour_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
