# Generated by Django 5.2.8 on 2026-03-26 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_bike_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike',
            options={'ordering': ['rank'], 'verbose_name': 'Bike', 'verbose_name_plural': 'Bikes'},
        ),
        migrations.AddField(
            model_name='booking',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_bookings', to='accounts.coupon'),
        ),
    ]
