# Generated by Django 5.2.8 on 2026-03-26 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_bike_options_booking_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
