# Generated by Django 5.2.8 on 2026-03-04 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_add_cvr_number_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SouvenirPickuplocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('other_info', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='souvenir_pickup_locations/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'souvenir pickuplocation',
                'verbose_name_plural': 'souvenir pickuplocations',
                'ordering': ['-created_at'],
            },
        ),
    ]
