# Generated by Django 5.2.8 on 2026-05-07 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_souvinir_pickuplocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='souvenirorder',
            name='delivery_method',
            field=models.CharField(choices=[('shipping', 'Shipping'), ('pickup', 'Pickup')], default='shipping', max_length=20),
        ),
        migrations.AddField(
            model_name='souvenirorder',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='souvenirorder',
            name='pickup_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.souvenirpickuplocation'),
        ),
        migrations.AddField(
            model_name='souvenirorder',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='souvenirorder',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='souvenirorder',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='souvenirorder',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
