# Generated by Django 5.2.8 on 2026-06-02 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_timeslots', to='accounts.timeslot')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_timeslots', to='accounts.tour')),
            ],
            options={
                'verbose_name': 'tour time slot',
                'verbose_name_plural': 'tour time slots',
                'unique_together': {('tour', 'time_slot')},
            },
        ),
    ]
