# Generated by Django 5.2.8 on 2026-06-02 10:16

import django.db.models.deletion
from django.db import migrations, models


def clear_invalid_tour_time_slot(apps, schema_editor):
    Booking = apps.get_model('accounts', 'Booking')
    # Set any existing string values to NULL before converting to ForeignKey
    Booking.objects.filter(tour_time_slot__isnull=False).update(tour_time_slot=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_tourtimeslot'),
    ]

    operations = [
        migrations.RunPython(clear_invalid_tour_time_slot, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='booking',
            name='tour_time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tourtimeslot'),
        ),
    ]
