# Generated by Django 5.2.8 on 2026-05-07 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_add_shipping_charge_to_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='CustomerReviewStatic',
            name='provider',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
