# Generated by Django 5.2.8 on 2026-05-07 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_add_provider_to_review_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='CustomerReviewStatic',
            name='otherinfo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='CustomerReviewStatic',
            name='providerimage',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='provider_images/'),
        ),
    ]